version: "1.0"

services:
  db:
    image: mysql:latest
    container_name: employees-management
    restart: always
    environment:
      MYSQL_DATABASE: "employees"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "aScaryLongPassword2000!"
      MYSQL_ROOT_PASSWORD: "aScaryLongRootPassword2000!"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    expose:
      - "3306"
